"""update enquiries rows

Revision ID: 01a7c2b787d0
Revises: 64f69cae10f5
Create Date: 2026-06-27 00:38:13.255640

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01a7c2b787d0"
down_revision: str | None = "64f69cae10f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("enquiries", sa.Column("class_applied", sa.String(), nullable=False))
    op.drop_column("enquiries", "desired_class")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enquiries", sa.Column("desired_class", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("enquiries", "class_applied")
    # ### end Alembic commands ###
