"""replace academic_terms list with term settings singleton

Revision ID: 024c6e0fd060
Revises: b2febbff4671
Create Date: 2026-09-14 21:55:43.063302

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "024c6e0fd060"
down_revision: str | None = "b2febbff4671"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_term_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("labels", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("current_label", sa.Text(), nullable=True),
        sa.Column("current_year", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id"),
    )

    op.drop_index("ix_academic_terms_tenant_id", table_name="academic_terms")
    op.drop_table("academic_terms")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_terms",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("label", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("is_current", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="academic_terms_tenant_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="academic_terms_pkey"),
    )
    op.create_index("ix_academic_terms_tenant_id", "academic_terms", ["tenant_id"], unique=False)

    op.drop_table("academic_term_settings")
    # ### end Alembic commands ###
