"""

Revision ID: 07b3ebb5c7c7
Revises: a1d2cfe0efff
Create Date: 2026-07-04 02:07:09.368344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b3ebb5c7c7'
down_revision: Union[str, None] = 'a1d2cfe0efff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('fees', sa.JSON(), nullable=True))
    op.drop_column('tenant_profiles', 'address')
    op.drop_column('tenant_profiles', 'website')
    op.drop_column('tenant_profiles', 'email')
    op.drop_column('tenant_profiles', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tenant_profiles', 'fees')
    # ### end Alembic commands ###
