"""update tenant

Revision ID: 28be48022ad4
Revises: 638005e0fb56
Create Date: 2026-06-23 23:26:27.064146

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "28be48022ad4"
down_revision: str | None = "638005e0fb56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
