"""update enquiries new rows

Revision ID: 3229f4ce549d
Revises: d3fb2bbabc14
Create Date: 2026-06-27 01:13:01.194457

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3229f4ce549d"
down_revision: str | None = "d3fb2bbabc14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enquiries", "assigned_to")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enquiries", sa.Column("assigned_to", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
