"""update tenant

Revision ID: 40dd68b652df
Revises: 28be48022ad4
Create Date: 2026-06-23 23:33:11.891645

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40dd68b652df"
down_revision: str | None = "28be48022ad4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("workspace_id", sa.String(), nullable=False))
    op.create_index(op.f("ix_tenants_workspace_id"), "tenants", ["workspace_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_workspace_id"), table_name="tenants")
    op.drop_column("tenants", "workspace_id")
    # ### end Alembic commands ###
