"""

Revision ID: 5f117afe3939
Revises: 0a9b43d7b313
Create Date: 2026-07-01 13:54:11.231692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f117afe3939'
down_revision: Union[str, None] = '0a9b43d7b313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profiles', sa.Column('cover_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_profiles', 'cover_image')
    # ### end Alembic commands ###
