"""

Revision ID: 6179f314aa68
Revises: decae5a53467
Create Date: 2026-07-14 20:41:50.438928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6179f314aa68'
down_revision: Union[str, None] = 'decae5a53467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_parent', 'student_parents', ['student_id', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_parent', 'student_parents', type_='unique')
    # ### end Alembic commands ###
