"""update scheemas

Revision ID: 638005e0fb56
Revises: 3b91a7b91874
Create Date: 2026-06-23 23:11:31.930550

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '638005e0fb56'
down_revision: str | None = '3b91a7b91874'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.alter_column('tenant_members', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tenant_members', 'joined_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('tenant_members', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_unique_constraint('uq_tenant_user', 'tenant_members', ['tenant_id', 'user_id'])
    op.create_foreign_key(None, 'tenant_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tenant_members', 'roles', ['role_id'], ['id'])
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_column('tenants', 'plan')
    op.drop_column('tenants', 'seat_limit')
    op.drop_column('tenants', 'stripe_subscription_id')
    op.drop_column('tenants', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('seat_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.alter_column('tenants', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'tenant_members', type_='foreignkey')
    op.drop_constraint(None, 'tenant_members', type_='foreignkey')
    op.drop_constraint('uq_tenant_user', 'tenant_members', type_='unique')
    op.alter_column('tenant_members', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('tenant_members', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('tenant_members', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
