"""updae enquiries

Revision ID: 64f69cae10f5
Revises: ff7a7803983d
Create Date: 2026-06-26 01:46:55.452411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f69cae10f5'
down_revision: Union[str, None] = 'ff7a7803983d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('officer', sa.String(), nullable=False))
    op.add_column('enquiries', sa.Column('previous_school', sa.String(), nullable=True))
    op.add_column('enquiries', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'notes')
    op.drop_column('enquiries', 'previous_school')
    op.drop_column('enquiries', 'officer')
    # ### end Alembic commands ###
