"""replace class_subjects with subject_classes

Revision ID: 6c129f108666
Revises: 3aae681fab24
Create Date: 2026-09-14 18:30:37.115814

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c129f108666"
down_revision: str | None = "3aae681fab24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subject_classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_subject_classes_tenant_id", "subject_classes", ["tenant_id"], unique=False)

    op.drop_index("ix_class_subjects_tenant_id", table_name="class_subjects")
    op.drop_table("class_subjects")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class_subjects",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("class_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subject_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["school_classes.id"],
            name="class_subjects_class_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name="class_subjects_subject_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="class_subjects_tenant_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="class_subjects_pkey"),
        sa.UniqueConstraint("class_id", "subject_id", name="uq_class_subject"),
    )
    op.create_index("ix_class_subjects_tenant_id", "class_subjects", ["tenant_id"], unique=False)

    op.drop_index("ix_subject_classes_tenant_id", table_name="subject_classes")
    op.drop_table("subject_classes")
    # ### end Alembic commands ###
