"""

Revision ID: 6c19e859b218
Revises: d4f3645d7f50
Create Date: 2026-07-02 00:29:22.327709

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6c19e859b218"
down_revision: str | None = "d4f3645d7f50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
