"""add performance records

Revision ID: 7e1479cd7be6
Revises: 024c6e0fd060
Create Date: 2026-09-14 22:57:28.650291

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e1479cd7be6"
down_revision: str | None = "024c6e0fd060"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "performance_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("class_name", sa.Text(), nullable=False),
        sa.Column("term_label", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("student_name", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("score", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "class_name",
            "term_label",
            "year",
            "student_name",
            "subject",
            name="uq_performance_record",
        ),
    )
    op.create_index(
        "ix_performance_records_lookup",
        "performance_records",
        ["tenant_id", "class_name", "term_label", "year"],
        unique=False,
    )
    op.create_index(
        "ix_performance_records_tenant_id", "performance_records", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_performance_records_tenant_id", table_name="performance_records")
    op.drop_index("ix_performance_records_lookup", table_name="performance_records")
    op.drop_table("performance_records")
    # ### end Alembic commands ###
