"""update tenant

Revision ID: 878e3571fdf8
Revises: e284877137fc
Create Date: 2026-06-24 09:58:55.865843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878e3571fdf8'
down_revision: Union[str, None] = 'e284877137fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_path')
    # ### end Alembic commands ###
