"""add student medical profile

Revision ID: 8fdabbfbde24
Revises: 6179f314aa68
Create Date: 2026-07-18 17:41:15.758266

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8fdabbfbde24"
down_revision: str | None = "6179f314aa68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_medical_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("blood_type", sa.Text(), nullable=True),
        sa.Column("emergency_notes", sa.Text(), nullable=True),
        sa.Column("doctor_name", sa.Text(), nullable=True),
        sa.Column("doctor_phone", sa.Text(), nullable=True),
        sa.Column("clinic_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id"),
    )
    op.create_index(
        "ix_medical_profiles_tenant_id", "student_medical_profiles", ["tenant_id"], unique=False
    )

    op.create_table(
        "student_allergies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("reaction", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["student_medical_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_allergies_tenant_id", "student_allergies", ["tenant_id"], unique=False)

    op.create_table(
        "student_medical_conditions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["student_medical_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conditions_tenant_id", "student_medical_conditions", ["tenant_id"], unique=False
    )

    op.create_table(
        "student_medications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("dosage", sa.Text(), nullable=True),
        sa.Column("frequency", sa.Text(), nullable=True),
        sa.Column("time", sa.Text(), nullable=True),
        sa.Column("prescribed_by", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["student_medical_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_medications_tenant_id", "student_medications", ["tenant_id"], unique=False)

    op.drop_table("student_medical_notes")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "student_medical_notes",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("note", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "health_conditions",
            sa.JSON(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("allergies", sa.JSON(), autoincrement=False, nullable=True),
        sa.Column(
            "medications",
            sa.JSON(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("doctor", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name="student_medical_notes_student_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="student_medical_notes_tenant_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="student_medical_notes_pkey"),
    )

    op.drop_index("ix_medications_tenant_id", table_name="student_medications")
    op.drop_table("student_medications")
    op.drop_index("ix_conditions_tenant_id", table_name="student_medical_conditions")
    op.drop_table("student_medical_conditions")
    op.drop_index("ix_allergies_tenant_id", table_name="student_allergies")
    op.drop_table("student_allergies")
    op.drop_index("ix_medical_profiles_tenant_id", table_name="student_medical_profiles")
    op.drop_table("student_medical_profiles")
    # ### end Alembic commands ###
