"""

Revision ID: a1d2cfe0efff
Revises: 6c19e859b218
Create Date: 2026-07-02 00:49:31.501578

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1d2cfe0efff"
down_revision: str | None = "6c19e859b218"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenant_profiles", sa.Column("mode", sa.String(), nullable=True))
    op.drop_column("tenant_profiles", "boarding")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant_profiles", sa.Column("boarding", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("tenant_profiles", "mode")
    # ### end Alembic commands ###
