"""add student attendance profile

Revision ID: b1f37a4510e6
Revises: 28e7bef3a66d
Create Date: 2026-09-14 13:53:06.805707

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1f37a4510e6"
down_revision: str | None = "28e7bef3a66d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_attendance_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id"),
    )
    op.create_index(
        "ix_attendance_profiles_tenant_id",
        "student_attendance_profiles",
        ["tenant_id"],
        unique=False,
    )

    op.create_table(
        "student_attendance_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["student_attendance_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_attendance_records_tenant_id", "student_attendance_records", ["tenant_id"], unique=False
    )

    op.drop_table("student_attendance")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_attendance",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("date", sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column("status", sa.String(), autoincrement=False, nullable=False),
        sa.Column("reason", sa.String(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name="student_attendance_student_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="student_attendance_tenant_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="student_attendance_pkey"),
    )

    op.drop_index("ix_attendance_records_tenant_id", table_name="student_attendance_records")
    op.drop_table("student_attendance_records")
    op.drop_index("ix_attendance_profiles_tenant_id", table_name="student_attendance_profiles")
    op.drop_table("student_attendance_profiles")
    # ### end Alembic commands ###
