"""add study format to students

Revision ID: c60f833818f8
Revises: 6ff9a5818d89
Create Date: 2026-07-14 00:03:10.380632

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c60f833818f8"
down_revision: str | None = "6ff9a5818d89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_student_parent', 'student_parents', ['student_id', 'parent_id'])
    op.add_column("students", sa.Column("study_format", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "study_format")
    # op.drop_constraint('uq_student_parent', 'student_parents', type_='unique')
    # ### end Alembic commands ###
