"""

Revision ID: ce0198a17afa
Revises: c60f833818f8
Create Date: 2026-07-14 20:31:15.931124

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce0198a17afa"
down_revision: str | None = "c60f833818f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parents", sa.Column("name", sa.String(length=100), nullable=False))
    op.add_column("parents", sa.Column("proof_of_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parents", "proof_of_id")
    op.drop_column("parents", "name")
    # ### end Alembic commands ###
