"""update enquiries new rows

Revision ID: d3fb2bbabc14
Revises: 01a7c2b787d0
Create Date: 2026-06-27 01:11:07.549169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3fb2bbabc14'
down_revision: Union[str, None] = '01a7c2b787d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('name', sa.String(), nullable=False))
    op.add_column('enquiries', sa.Column('parent', sa.String(), nullable=True))
    op.add_column('enquiries', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('enquiries', sa.Column('email', sa.String(), nullable=True))
    op.add_column('enquiries', sa.Column('stage', sa.String(), nullable=False))
    op.drop_column('enquiries', 'parent_email')
    op.drop_column('enquiries', 'status')
    op.drop_column('enquiries', 'parent_name')
    op.drop_column('enquiries', 'parent_phone')
    op.drop_column('enquiries', 'student_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('student_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('enquiries', sa.Column('parent_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('enquiries', sa.Column('parent_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('enquiries', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('enquiries', sa.Column('parent_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('enquiries', 'stage')
    op.drop_column('enquiries', 'email')
    op.drop_column('enquiries', 'phone')
    op.drop_column('enquiries', 'parent')
    op.drop_column('enquiries', 'name')
    # ### end Alembic commands ###
