"""

Revision ID: d4f3645d7f50
Revises: c8e98d9926bc
Create Date: 2026-07-02 00:19:14.573277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f3645d7f50'
down_revision: Union[str, None] = 'c8e98d9926bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('curriculum', sa.JSON(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('subjects', sa.JSON(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('levels', sa.JSON(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('type', sa.String(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('founded', sa.String(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('boarding', sa.String(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('location', sa.JSON(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('contact', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_profiles', 'contact')
    op.drop_column('tenant_profiles', 'location')
    op.drop_column('tenant_profiles', 'boarding')
    op.drop_column('tenant_profiles', 'founded')
    op.drop_column('tenant_profiles', 'gender')
    op.drop_column('tenant_profiles', 'type')
    op.drop_column('tenant_profiles', 'levels')
    op.drop_column('tenant_profiles', 'subjects')
    op.drop_column('tenant_profiles', 'curriculum')
    # ### end Alembic commands ###
