"""update tenant

Revision ID: db62d5d25d26
Revises: 40dd68b652df
Create Date: 2026-06-24 00:24:03.412538

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db62d5d25d26"
down_revision: str | None = "40dd68b652df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("plan", sa.String(), nullable=True))
    op.create_index(op.f("ix_tenants_plan"), "tenants", ["plan"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_plan"), table_name="tenants")
    op.drop_column("tenants", "plan")
    # ### end Alembic commands ###
