"""

Revision ID: decae5a53467
Revises: ce0198a17afa
Create Date: 2026-07-14 20:33:29.587364

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "decae5a53467"
down_revision: str | None = "ce0198a17afa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parents", "first_name")
    op.drop_column("parents", "last_name")
    # op.create_unique_constraint('uq_student_parent', 'student_parents', ['student_id', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_student_parent', 'student_parents', type_='unique')
    op.add_column(
        "parents",
        sa.Column("last_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "parents",
        sa.Column("first_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
