"""update tenant

Revision ID: e284877137fc
Revises: db62d5d25d26
Create Date: 2026-06-24 07:59:24.520583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e284877137fc'
down_revision: Union[str, None] = 'db62d5d25d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_members_tenant_id_fkey', 'tenant_members', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_members', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_members', type_='foreignkey')
    op.create_foreign_key('tenant_members_tenant_id_fkey', 'tenant_members', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
